name: TestRigor Bank App Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-testrigor-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger TestRigor test suite
        run: |
          # Trigger the test suite
          response=$(curl -s -X POST \
            -H 'Content-type: application/json' \
            -H 'auth-token: 2e1076d8-69a2-479f-8ee9-218e6cbd305f' \
            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
            https://api.testrigor.com/api/v1/apps/ppAQmiFMGDoG3u7fb/retest)
          echo "Triggered test suite"
          echo "$response"
          sleep 10

          # Polling the test status
          while true; do
            echo " "
            echo "==================================="
            echo " Checking run status"
            echo "==================================="
            
            status_response=$(curl -s -X GET \
              -H 'auth-token: 2e1076d8-69a2-479f-8ee9-218e6cbd305f' \
              -H 'Accept: application/json' \
              https://api.testrigor.com/api/v1/apps/ppAQmiFMGDoG3u7fb/status)
            
            code=$(echo "$status_response" | jq -r '.statusCode')
            echo "Response: $status_response"
            echo "Status code: $code"
            
            case $code in
              4??|5??)
                echo "Error calling API"
                exit 1
                ;;
              200)
                echo "Test finished successfully"
                exit 0
                ;;
              227|228)
                echo "Test is not finished yet"
                ;;
              229)
                echo "Test canceled"
                exit 1
                ;;
              230)
                echo "Test finished but failed"
                exit 1
                ;;
              *)
                echo "Unknown status"
                exit 1
                ;;
            esac
            sleep 10
          done
